### ISSUE TITLE
What is the difference between this module and `nuxt-modules/mdc` ?

### ISSUE THREAD

**Issue by stefanobartoletti** [Sandros94/nuxt-markdown-render#7]
Thanks for releasing this module!

I'm doing some research to find what works best in my case to parse markdown, and I'm curious about what are the differences between your own module and https://github.com/nuxt-modules/mdc

Thanks!

**Comment by sandros94** [comment]
In a nutshell, they use different markdown processors with different plugin ecosystems. `@nuxtjs/mdc` is based on [remark](https://github.com/remarkjs/remark) while `nuxt-markdown-render` on [markdown-it](https://github.com/markdown-it/markdown-it).

I wouldn't even really compare their performance either, since they are vastly based on their current configuration and plugins at use.

Personally, I use them both.
With the main difference that I tend to use `nuxt-markdown-render` when I manage markdown outside of Nuxt (like fetched from a backend), while Nuxt's mdc (or content) when doing it _in house_.

**Comment by stefanobartoletti** [comment]
Thanks!

**Comment by sandros94** [comment]
Feel free to comment or reopen this issue if you have anything in mind!
